#!/usr/bin/env zsh

set -e
set -u
set -o pipefail

cd ${0:h}
ROOT=${PWD:h:h:a}

eval $(make --no-print-directory --file="${ROOT}/vars.mk" bash)

STATE_FILE=$1
HOST=$(terraform output -state="${ROOT}/machines/ml/${STATE_FILE}" controller-host)
# TODO(sergio): change it downstream so that we always use ENVIRONMENT_NAME
AWS_AUTOSCALING_GROUP=$ENVIRONMENT_NAME
SSH_PRIVATE_KEY_FILE="${ROOT}/machines/keys/batman.privkey"
TAG=$(make --no-print-directory tag)
IMAGE=$(docker inspect $TAG | jq -r '.[0].RepoDigests[0]')
SERVICE_PORT=80

ANSIBLE_INVENTORY=$(mktemp "${TMPDIR:-/tmp/}inventory-XXXXX")
cat > $ANSIBLE_INVENTORY <<EOF
---
all:
  hosts:
    ${HOST}:
      ansible_user: "ubuntu"
      ansible_ssh_private_key_file: "${SSH_PRIVATE_KEY_FILE}"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  vars:
    aws_region: "${AWS_REGION}"
    aws_project: "${AWS_PROJECT}"
    aws_autoscaling_group: "${AWS_AUTOSCALING_GROUP}"
    image: "${IMAGE}"
    service_port: "${SERVICE_PORT}"
    ssh_private_key_file: "${SSH_PRIVATE_KEY_FILE}"
EOF
export ANSIBLE_INVENTORY

ansible-playbook playbook.yml

rm -f $ANSIBLE_INVENTORY
