#!/bin/bash

set -e
set -u

cd "$(dirname "${BASH_SOURCE[0]}")"

mkdir -p ../../cache/controller
DEFAULT_DATA_DIR="$(cd ../../cache/controller && pwd)"

if [[ -z "${DATA_DIR:-}" ]]; then
  export DATA_DIR="$DEFAULT_DATA_DIR"
fi

export TEMP_DATA_DIR="${DATA_DIR}/tmp"
mkdir -p "${DATA_DIR}"
mkdir -p "${TEMP_DATA_DIR}"

export PYTHONPATH=./src

exec gunicorn \
  --bind="0.0.0.0:${PORT:-8080}" \
  --preload \
  --workers=1 \
  --timeout=120 \
  --pythonpath=${PYTHONPATH} \
  plz.controller.main:app \
  -- $@
