#!/usr/bin/env bash

set -e
set -u

if command -v realpath > /dev/null; then
  ROOT="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")" && pwd)"
else
  ROOT="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
fi

if ! command -v pipenv > /dev/null; then
  # shellcheck disable=SC2016
  echo >&2 'Could not find `pipenv`.'
  exit 2
fi

PYTHON="$(cd "${ROOT}/cli" && pipenv --venv)/bin/python"

PYTHONPATH="${ROOT}/cli/src" "${PYTHON}" "${ROOT}/cli/src/plz/cli/main.py" "$@"
