#!/bin/sh

docker build -q harvester/

BUILD_TIMESTAMP=`cat BUILD_TIMESTAMP` \
  SECRETS_DIR=$PWD/aws_config \
  REDIS_DUMP_EVERY_SECONDS=2 \
  docker-compose up -d --no-build prebuilt_local_controller_aws
