#!/bin/sh

docker pull prodoai/plz_ml-pytorch
docker pull python:3-slim
docker pull "prodoai/plz_controller:timestamp_$(cat STABLE_BUILD_TIMESTAMP)"

BUILD_TIMESTAMP=$(cat STABLE_BUILD_TIMESTAMP) \
    REDIS_DUMP_EVERY_SECONDS=2 \
    LOG_LEVEL=${LOG_LEVEL:-WARNING} \
    docker-compose up -d --no-build prebuilt_controller_localhost

docker-compose logs -f &
