#!/usr/bin/env zsh

set -e
set -u

cd $(dirname $0)

HOST=$1
PORT=22

SSH_PRIVATE_KEY_FILE=../keys/batman.privkey
chmod go-rwx $SSH_PRIVATE_KEY_FILE

ANSIBLE_INVENTORY=$(mktemp)
echo "${HOST} ansible_user=ubuntu ansible_ssh_private_key_file=${SSH_PRIVATE_KEY_FILE:h} ansible_ssh_extra_args='-o ConnectTimeout=300'" \
  > $ANSIBLE_INVENTORY

start=$(date +%s)
timeout=60
while ! nc -z $HOST $PORT >& /dev/null; do
  sleep 1
  now=$(date +%s)
  if [[ $((start + timeout)) -lt $now ]]; then
    echo >&2 "Could not connect to ${HOST}."
    exit 1
  fi
done

export ANSIBLE_HOST_KEY_CHECKING=false
export ANSIBLE_INVENTORY
ansible-playbook cache.yml

rm -f $ANSIBLE_INVENTORY
