#!/bin/bash

# This is copied to a host and run by Terraform after creation.
#
# It sets up the cache volume used to cache Docker images and other large files.

set -e
set -u

if [[ "$(id -u)" -ne 0 ]]; then
  exec sudo "$0" "$@"
fi

DEVICE="$1"
MOUNTPOINT='/cache'
FSTYPE='ext4'

if [[ ! -b "$DEVICE" ]]; then
  echo >&2 "${DEVICE} is not a block device."
  exit 1
fi

mkdir -p "$MOUNTPOINT"

if [[ "$(file -s "$DEVICE")" == "${DEVICE}: data" ]]; then
  mkfs -t "$FSTYPE" "$DEVICE"
fi

echo "${DEVICE} ${MOUNTPOINT} ${FSTYPE} defaults 0 0" > /etc/fstab
mount "$MOUNTPOINT"

addgroup cache
chown root:cache "$MOUNTPOINT"
chmod u+rwx,g+rws,o-rwx "$MOUNTPOINT"

mkdir -p "${MOUNTPOINT}/docker"
service docker stop
rm -rf /var/lib/docker
ln -s "${MOUNTPOINT}/docker" /var/lib/docker
service docker start
