#!/usr/bin/env zsh

set -e
set -u

cd $(dirname $0)

if [[ ! -d .terraform ]]; then
  terraform init
fi
terraform get
terraform apply

ssh_private_key_file=${PWD}/../keys/batman.privkey
ssh_private_key_file=${ssh_private_key_file:A}
chmod go-rwx $ssh_private_key_file
ssh=(ssh -i $ssh_private_key_file)
build_host=$(jq -r '.modules[0].resources["aws_instance.build"].primary.attributes.public_dns' < terraform.tfstate)
experiments_host=$(jq -r '.modules[0].resources["aws_spot_instance_request.experiments"].primary.attributes.public_dns' < terraform.tfstate)
cat > inventory <<EOF
[build]
${build_host} ansible_user=ubuntu ansible_ssh_private_key_file=${ssh_private_key_file}

[experiments]
${experiments_host} ansible_user=ubuntu ansible_ssh_private_key_file=${ssh_private_key_file}
EOF

export ANSIBLE_HOST_KEY_CHECKING=false
export ANSIBLE_INVENTORY=${PWD}/inventory

ansible all -m raw -a 'command -v python || ( sudo apt-get update -q && sudo apt-get install -qy python )'
ansible-playbook playbook.yml
