#!/usr/bin/env zsh

set -e
set -u

cd $(dirname $0)

if [[ ! -d .terraform ]]; then
  terraform init
fi
terraform get
terraform apply

ssh_private_key_file=../keys/batman.privkey
chmod go-rwx $ssh_private_key_file
ssh=(ssh -i $ssh_private_key_file)
build_host=$(terraform output build-host)
experiments_host=$(terraform output experiments-host)
cat > inventory <<EOF
[build]
${build_host} ansible_user=ubuntu ansible_ssh_private_key_file=${ssh_private_key_file} ansible_ssh_extra_args='-o ConnectTimeout=60'

[experiments]
${experiments_host} ansible_user=ubuntu ansible_ssh_private_key_file=${ssh_private_key_file} ansible_ssh_extra_args='-o ConnectTimeout=60'
EOF

export ANSIBLE_HOST_KEY_CHECKING=false
export ANSIBLE_INVENTORY=${PWD}/inventory

ansible all --one-line --module-name=raw --args='command -v python || ( sudo apt-get update -qq && sudo apt-get install -qqy python )'
ansible-playbook playbook.yml
