#!/usr/bin/env zsh

set -e
set -u
set -o pipefail

ROOT=${PWD:h:h:a}

eval $(make --no-print-directory --file="${ROOT}/vars.mk" bash)

HOST=$1
PLAYBOOK=$2
SSH_PRIVATE_KEY_FILE="${ROOT}/machines/keys/plz.privkey"

ANSIBLE_INVENTORY=$(mktemp "${TMPDIR:-/tmp/}inventory-XXXXX")
cat > $ANSIBLE_INVENTORY <<EOF
---
all:
  hosts:
    ${HOST}:
      ansible_user: "ubuntu"
      ansible_ssh_private_key_file: "${SSH_PRIVATE_KEY_FILE}"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
EOF
export ANSIBLE_INVENTORY

ansible-playbook $PLAYBOOK

rm -f $ANSIBLE_INVENTORY
