#!/usr/bin/env zsh

set -e
set -u
set -o pipefail

ROOT=${0:a:h:h}

PLAYBOOK=${1:a}
HOSTNAME=$2
shift
shift

PLAYBOOK_ARGS=()
while [[ $# -gt 0 ]]; do
  PLAYBOOK_ARGS+=(--extra-vars "@${1}")
  shift
done

eval $(make --no-print-directory --file="${ROOT}/vars.mk" bash)

HOST_IP=$(dig +short $HOSTNAME)
if [[ -z $HOST_IP ]]; then
  echo >&2 "Could not resolve ${HOSTNAME}."
  exit 1
fi

SSH_PRIVATE_KEY_FILE="${ROOT}/machines/keys/plz.privkey"

ANSIBLE_INVENTORY=$(mktemp "${TMPDIR:-/tmp/}inventory-XXXXX")
cat > $ANSIBLE_INVENTORY <<EOF
---
all:
  hosts:
    ${HOST_IP}:
      ansible_user: "ubuntu"
      ansible_ssh_private_key_file: "${SSH_PRIVATE_KEY_FILE}"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  vars:
    aws_region: "${AWS_REGION}"
    aws_project: "${AWS_PROJECT}"
    environment_name: "${ENVIRONMENT_NAME}"
    ssh_private_key_file: "${SSH_PRIVATE_KEY_FILE}"
EOF

ansible-playbook --inventory=$ANSIBLE_INVENTORY $PLAYBOOK_ARGS $PLAYBOOK

rm -f $ANSIBLE_INVENTORY
