#!/usr/bin/env bash

set -eu

while true; do
  sleep "$WAIT_FOR_SECONDS"
  echo 'Harvesting...'
  if curl -fsS -X POST "${HOST}:${PORT}/executions/harvest" > /dev/null; then
    echo 'Harvesting complete. You can run plz commands now'
  else
    echo 'Error harvesting!'
  fi
done
