#!/usr/bin/env bash

set -eu

while true; do
  echo 'Harvesting...'
  if curl -fsS -X POST "${HOST}:${PORT}/executions/harvest" > /dev/null; then
    echo 'Harvesting complete.'
  else
    echo 'Error harvesting!'
  fi
  sleep "$WAIT_FOR_SECONDS"
done
