#!/usr/bin/env bash

set -e
set -u

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"

docker build ${DIR}/../harvester -t plz/harvester

BUILD_TIMESTAMP="$(cat ${DIR}/../STABLE_BUILD_TIMESTAMP)" \
  LOG_LEVEL="${LOG_LEVEL:-WARNING}" \
  docker-compose --project-name=plz --file="${DIR}/local-prebuilt.yml" up --no-build "$@"
