#!/bin/bash

# This file is required because setting the PATH or PYTHONPATH
# self-referentially when building the Docker image doesn't work with Packer.
# This is because it uses `docker commit --change`, which appears to have a bug
# in its handling of environment variables.
#
# More information can be found at:
# https://github.com/moby/moby/pull/35582

export PATH="${ANACONDA_DIR}/envs/${ANACONDA_ENV}/bin:${ANACONDA_DIR}/bin:${PATH}"
export PYTHONPATH=".:${PYTHONPATH}"

exec "$@"
